### ISSUE TITLE
problem with bachelor lesson 2.25.16

### ISSUE THREAD

**Issue by jd2rogers2** [learn-co-curriculum/the-bachelor-todo#12]
![screen shot 2016-02-25 at 1 41 47 pm](https://cloud.githubusercontent.com/assets/16400333/13330165/896b25f8-dbc5-11e5-8ad9-228e639618d0.png)

this shouldn't return "fail" it should return all the season keys from the first hash
checked with others who have passed this lesson and theirs passed with the way I have it now

**Comment by maxwellbenton** [comment]
Hi @jd2rogers2,

Thank you for opening this issue. We've recently updated this lesson and incorporated changes based on your feedback. The issue is related to the behavior of the JSON parser, as it does not automatically convert string keys to symbols, unlike the default Ruby behavior when creating hashes. We've added in a note regarding this, which should help guide students in the future.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
