### ISSUE TITLE
Issue using JSON data when testing spec

### ISSUE THREAD

**Issue by jamesvphan** [learn-co-curriculum/the-bachelor-todo#13]
When completing the methods for this exercise, I was given an error that my return value was not the expected value. However, I tested my method using repl.it after editing the data to utilize "=>" notation when assigning hashes, rather than the ":" the JSON file used (i.e. "season 19 : []) I'm not sure if this was supposed to affect my syntax when writing my solution, but even knowing my solution was correct, I could not get the spec to work. However, when using "=>" to assign my hashes, my solutions gave no error.

**Comment by maxwellbenton** [comment]
Hi @jamesvphan,

Thank you for opening this issue. We've recently updated this lesson and incorporated changes based on your feedback. The issue is related to the behavior of the JSON parser, as it does not automatically convert string keys to symbols, unlike the default Ruby behavior when creating hashes. We've added in a note regarding this, which should help guide students in the future.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
