### ISSUE TITLE
learn.co reading strings instead of symbols

### ISSUE THREAD

**Issue by mikemerin** [learn-co-curriculum/the-bachelor-todo#14]
When reading through a hash:

{"name":"Ashley Iaconetti"} should become {:"name" => "Ashley Iaconetti"}

where the key's class is a symbol :"name" (doing hash.key.class should give symbol)

However instead it is reading the hash as {"name" => "Ashley Iaconetti"}

where the key's class is a string "name" which is incorrect.

Because of this, data["season 19"] gives data instead of the correct data[:"season 19"]

**Comment by maxwellbenton** [comment]
Hi @mikemerin!

The issue is related to the behavior of the JSON parser, as it does not automatically convert string keys to symbols, (unlike the default Ruby behavior). We've added in a note regarding this, which should help guide students in the future.

Thanks for pointing this out. Hope you are well, my friend!
