### ISSUE TITLE
Tests returning incorrect value

### ISSUE THREAD

**Issue by bmcilhenny** [learn-co-curriculum/the-bachelor-todo#15]
`Failures:
  1) bachelor #get_first_name_of_season_winner returns 'Tessa' when passed the data and 'season 10'
     Failure/Error: expect(get_first_name_of_season_winner(data, "season 10")).to eq("Tessa")
       expected: "Tessa"
            got: {"season 19"=>[{"name"=>"Ashley Iaconetti", "age"=>"26", "hometown"=>"Great Falls, Virginia", "occupa... Jacobs", "age"=>"23", "hometown"=>"C
hicago, Illinois", "occupation"=>"Model", "status"=>"Week 1"}]}
       (compared using ==)`

My repl.it works correctly, when testing in Learn IDE does not work: https://repl.it/LtBl/23.
Unsure what the issue is.

**Comment by marycodes2** [comment]
I am having the same exact issue. Please help!

**Comment by maxwellbenton** [comment]
Hi @bmcilhenny,

Thank you for opening this issue. We've recently updated this lesson and incorporated changes based on your feedback. The issue is related to the behavior of the JSON parser, as it does not automatically convert string keys to symbols, which is the default Ruby behavior. We've added in a note regarding this, which should help guide students in the future.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
